-- This query makes a new hydro_simple_scenario that is the median year of all WECC hydropower generation, repeated for every year in the time horizon from 2010 to 2070

-- 1. create new hydro simple scenario id 22 in the hydro simple mapping table
--INSERT INTO switch.hydro_simple_scenario (hydro_simple_scenario_id, name, description)
--VALUES (22, 'Median year repeated of total annual WECC hydropower generation from EIA923 datasets 2004 until 2018, --AMPL 2006 for Canada and Mexico', 'Median year (2007) repeated for 2010 through 2070, based on id 21 of EIA 2004 to --2018 data plus AMPL 2006 Basecase Canada and Mex hydro cf repeated for 2004 to 2018');

-- 2. Then copy the hydro capacity factors time series of the median year from scenario 21 (2007) and repeat for each year 2010 to 2070 in the new scenario .
-- the median year (2007) is the year ranked 8 out of 15 total years of historical data (2004 to 2018)

INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2010 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2011 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2012 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2013 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2014 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2015 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2016 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2017 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2018 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2019 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2020 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2021 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2022 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2023 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2024 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2025 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2026 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2027 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2028 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2029 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2030 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2031 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2032 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2033 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2034 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2035 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2036 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2037 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2038 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2039 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2040 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2041 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2042 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2043 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2044 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2045 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2046 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2047 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2048 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2049 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2050 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2051 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2052 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2053 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2054 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2055 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2056 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2057 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2058 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2059 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2060 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2061 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2062 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2063 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2064 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2065 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2066 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2067 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2068 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2069 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 22 as hydro_simple_scenario_id, a.generation_plant_id, 2070 as year, a.month, a.hydro_min_flow_mw, a.hydro_avg_flow_mw FROM switch.hydro_historical_monthly_capacity_factors a JOIN hydro_year_classification b ON a.year = b.year WHERE a.hydro_simple_scenario_id = 21 AND year_rank = 8;

