-- This query makes a new hydro_simple_scenario that is the average monthly generation from 2004 - 2018 by generation for all WECC hydropower generators, repeated for every year in the time horizon from 2010 to 2070

-- 1. create new hydro simple scenario id 23 in the hydro simple mapping table
--INSERT INTO switch.hydro_simple_scenario (hydro_simple_scenario_id, name, description)
--VALUES (23, 'Avg 2004 to 2018 monthly generation from EIA and AMPL Canada and Mex data repeated for each year', 'Monthly avg generation from 2004 to 2018 from EIA923 datasets, AMPL 2006 for Canada and Mexico repeated for 2010 through 2070, based on id 21');

-- 2. Then copy the hydro capacity factors time series of the average month generation from 2004 to 2018 from scenario 21 (2007) and repeat for each year 2010 to 2070 in the new scenario .


--INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw)
--SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2010 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw
--FROM hydro_avg_monthly_gen_2004_2018
--order by generation_plant_id, year, month;

INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2010 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2011 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2012 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2013 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2014 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2015 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2016 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2017 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2018 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2019 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2020 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2021 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2022 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2023 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2024 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2025 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2026 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2027 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2028 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2029 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2030 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2031 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2032 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2033 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2034 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2035 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2036 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2037 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2038 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2039 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2040 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2041 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2042 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2043 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2044 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2045 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2046 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2047 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2048 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2049 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2050 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2051 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2052 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2053 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2054 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2055 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2056 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2057 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2058 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2059 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2060 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2061 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2062 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2063 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2064 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2065 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2066 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2067 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2068 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2069 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
INSERT INTO switch.hydro_historical_monthly_capacity_factors (hydro_simple_scenario_id, generation_plant_id, year, month, hydro_min_flow_mw, hydro_avg_flow_mw) SELECT 23 as hydro_simple_scenario_id, generation_plant_id, 2070 as year, month, hydro_min_flow_mw, hydro_avg_flow_mw FROM hydro_avg_monthly_gen_2004_2018 order by generation_plant_id, year, month;
